name: logistic_management_customer
description: Logistic Management (Customer) Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ars_dialog: ^1.0.8
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  community_material_icon: ^5.9.55
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.5
  jiffy: ^5.0.0
  dio: ^4.0.6
  flash: ^2.0.3+3
  flutter_multi_formatter: ^2.6.0
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.1
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.10
  material_color_generator: ^1.1.0
  permission_handler: ^10.0.0
  pretty_json: ^2.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  timeline_tile: ^2.0.0
  validators: ^3.0.0
#  flutter_html: ^2.2.1
  url_launcher: ^6.1.5
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  flutter_svg: ^1.1.3
  geocoding: ^2.0.4
#  google_place: ^0.4.7

  device_info_plus: ^4.1.1

  firebase_core: ^1.20.1
  firebase_messaging: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  flutter_launcher_icons: ^0.10.0

flutter_icons:
  # image_path: "images/launcher/icon.png"
  ios: true
  android: true
  image_path_android: "images/launcher/icon.png"
  image_path_ios: "images/launcher/icon.png"
  adaptive_icon_background: "images/launcher/background.png"
  adaptive_icon_foreground: "images/launcher/foreground.png"
    

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/services/
