name: logistic_management_customer
description: Logistic Management (Customer) Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ars_dialog: ^1.0.8
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  community_material_icon: ^5.9.55
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.4
  jiffy: ^5.0.0
  dio: ^4.0.4
  flash: ^2.0.3+2
  flutter_multi_formatter: ^2.5.1
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.1.1
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.1
  material_color_generator: ^1.1.0
  permission_handler: ^8.3.0
  pretty_json: ^2.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  sliding_up_panel: ^2.0.0+1
  timeline_tile: ^2.0.0
  validators: ^3.0.0
#  flutter_html: ^2.2.1
  url_launcher: ^6.0.20
  image_picker: ^0.8.4+8
  image_cropper: ^1.4.1
  flutter_svg: ^1.0.3
  geocoding: ^2.0.2

  device_info_plus: ^3.2.1

  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  # image_path: "images/launcher/icon.png"
  ios: true
  android: true
  image_path_android: "images/launcher/icon.png"
  image_path_ios: "images/launcher/icon.png"
  adaptive_icon_background: "images/launcher/background.png"
  adaptive_icon_foreground: "images/launcher/foreground.png"
    

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/services/
